[package]
name = "atto"
version = "0.1.1"
edition = "2021"

[dependencies]
crossterm = "0.23.2"
tui = "0.19.0"
##tree-sitter = "0.23.0"
##tree-sitter-highlight = "0.23.0"
##tree-sitter-rust = "0.23.0"
##tree-sitter-c = "0.23.0"
##tree-sitter-haskell = "0.23.0"


[build-dependencies]

cc="*"
